config:
  credentials: []
  project_repos:
    github.com/Dans-labs/semaf-client:
      branch: master
      repo: https://github.com/Dans-labs/semaf-client
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Dans-labs/semaf-client git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-celadon-gecko.sh
        container: qc.acc_wiggy-seashell-peccary
  QC.Doc:
    repos:
      github.com/Dans-labs/semaf-client find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-heliotrope-tuatara.sh
        container: qc.doc_queasy-ivory-iguana
      github.com/Dans-labs/semaf-client git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-rust-zebu.sh
        container: qc.doc_goopy-lime-echidna
      github.com/Dans-labs/semaf-client markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-amaranth-mammoth.sh
        container: qc.doc_sunny-black-caiman
  QC.Lic:
    repos:
      github.com/Dans-labs/semaf-client licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-peach-collie.sh
        container: qc.lic_squeaky-amber-wildebeest
  QC.Sec:
    repos:
      github.com/Dans-labs/semaf-client bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-copper-hornet.sh
        container: qc.sec_greasy-denim-maltese
  QC.Sty:
    repos:
      github.com/Dans-labs/semaf-client flake8:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-lime-burmese.sh
        container: qc.sty_gamy-copper-chow
  QC.Ver:
    repos:
      github.com/Dans-labs/semaf-client get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-sangria-bonobo.sh
        container: qc.ver_lanky-aqua-chinchilla
timeout: 1800
